spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: employee-info
          uri: https://employee-microservice-example.onrender.com
          predicates:
            - Path=/employee/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-INFO
                fallbackUri: forward:/employeeServiceFallBack

        - id: department-info
          uri: https://department-microservice-example.onrender.com
          predicates:
            - Path=/department/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-INFO
                fallbackUri: forward:/departmentServiceFallBack

        - id: address-info
          uri: https://address-microservice-example.onrender.com
          predicates:
            - Path=/address/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: ADDRESS-INFO
                fallbackUri: forward:/addressServiceFallBack

        - id: auth-service
          uri: https://auth-service-example.onrender.com
          predicates:
            - Path=/auth/**

server:
  port: 8080
