spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employee-info
          uri: https://microservice-employee-service.onrender.com
          predicates:
            - Path=/employee/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-INFO
                fallbackUri: forward:/employeeServiceFallBack

        - id: department-info
          uri: https://microservice-department-service.onrender.com
          predicates:
            - Path=/department/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-INFO
                fallbackUri: forward:/departmentServiceFallBack

        - id: address-info
          uri: https://microservice-address-service.onrender.com
          predicates:
            - Path=/address/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: ADDRESS-INFO
                fallbackUri: forward:/addressServiceFallBack

        - id: auth-service
          uri: https://microservice-auth-service.onrender.com
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: https://microservice-service-registry-qgma.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 7777
